### ISSUE TITLE
No data after 2020-05-01T

### ISSUE THREAD

**Issue by vinbhai4u** [yedhink/covid19-kerala-api#13]
I tried the api https://covid19-kerala-api.herokuapp.com/api

I can find data till May 1st after that no data. Any issues?

**Comment by yedhink** [comment]
@vinbhai4u Thanks for raising the issue. It was caused by another inconsistency in the pdf table released on may 3rd and another major inconsistency in the html of http://dhs.kerala.gov.in/ bulletins page(the scraper looked for particular tag patterns, but they changed the tags at some entry points in their site). I have made a hotfix for that. Should be working now. Again thanks a lot for pointing out the issue. 

https://covid19-kerala-api.herokuapp.com/api/timeline
